- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: play variables from files
  hosts: localhost
  # var files only works on play level
  vars_files:
    - var.yml
  tasks:
    - name: print play variable from FILE
      ansible.builtin.debug:
        msg: URL = {{ URL }}