- name: play variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print play variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: play variables from files
  hosts: localhost
  # var files only works on play level
  vars_files:
    - user.service
  tasks:
    - name: print play variable from FILE
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: task variables
  hosts: localhost
  tasks:
    - name: Task level variable
      vars: # these are only for this task, next task on same play cannot access it.
        URL: play.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: variables from inventory
  hosts: all
  tasks:
    - name: print variable from inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }}